//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Payment
    {

     
        public int Id { get; set; }
        public Nullable<int> User_id { get; set; }
        [Required]

        public Nullable<int> Amount { get; set; }
        
        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy }", ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> Date_of_payment { get; set; }
    
        public virtual User User { get; set; }
    }
}
